server:
  port: 1201
spring:
  application:
    name: wjwcloud-config-eureka-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wjw0315/cloud-config-demo
          search-paths: repo
          clone-on-start: true
#          username:  # git用户名
#          password:  # git密码
        default-label: feature/wjw  # 默认分支


#Spring Cloud 服务注册
eureka:
  instance:
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 30
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
